server:
  port: 8001
  servlet:
    context-path: /ticket

spring:
  application:
    name: ticket-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/livecat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 8
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: 500
        max-idle: 20
        min-idle: 10

mybatis-plus:
  type-aliases-package: com.livecat.dto
  # xxxMapper.xml path
  mapper-locations: classpath*:com/livecat/event/mapper/**/*.xml,classpath*:com/livecat/ticket/mapper/**/*.xml

logging:
  level:
    com.livecat.event.mapper: debug

